project:
  type: website
  output-dir: docs

website:
  title: "Analyse Spatiale"
  navbar:
    left:
      - text: Syllabus
        href: Syllabus2025.qmd
      - text: 1. Introduction
        menu:
          - text: Cours1 - Qu'est-ce que l'analyse spatiale 
            href: cours1.qmd
          - text: TD1 - Jeux de cartes
            href: TD1.qmd
      - text: 2. Accessibilité
        menu:
          - text: Cours2 -  Accessibilité spatiale
            href: cours2.qmd
          - text: Focus -  Qu'est-ce qu'un désert médical ?
            href: cours2_diapo.qmd
            target: _blank
          - text: TD2 - Accessibilité aux services de soins
            href: https://analytics.huma-num.fr/Claude.Grasland/access/
            target: _blank
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/anspa
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025-2026, Claude Grasland & Malika Madelin
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


